/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.samirAtivacao.view;
import java.awt.*;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.samirAtivacao.controller.BancoController;
import com.samirAtivacao.controller.ControllerUsuario;
import com.samirAtivacao.controller.GeralController;
import com.samirAtivacao.modelo.Usuario;
import com.samirAtivacao.repository.SeleniumRepositorio;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

@SuppressWarnings("serial")
public class Beremiz extends javax.swing.JFrame {
    GeralController shazam = new GeralController();
    private Thread backgroundThread;

    /**
     * Creates new form beremiz
     * @throws SQLException 
     */
    public Beremiz() {
        initComponents();
        botaoSalvar.setBackground(new Color(0,0,0,0));
        botaoHome.setBackground(new Color(0,0,0,0));
        botaoParar.setForeground(Color.white);
        jLabel1.setForeground(Color.white);
        BancoController banco = new BancoController();
        Usuario usuario = new Usuario();
        usuario = banco.loginInformacoes();


        if (usuario.getNome() == null) {
            campoNome.setText("NOME");
        } else {
            campoNome.setText(usuario.getNome());
        }

        if (usuario.getEtiqueta() == null) {
            campoEtiqueta.setText("ETIQUETA");
        } else {
            campoEtiqueta.setText(usuario.getEtiqueta());
        }

        if (usuario.getCpf() == null) {
            campoCPF.setText("CPF");
        } else {
            campoCPF.setText(usuario.getCpf());
        }

        if (usuario.getSenha() == null) {
            campoSenha.setText("SENHA");
        } else {
            campoSenha.setText(usuario.getSenha());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoSalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoEtiqueta = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoParar = new javax.swing.JToggleButton();
        botaoIniciar = new javax.swing.JButton();
        botaoHome = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        botaoSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 14.png"))); // NOI18N
        botaoSalvar.setActionCommand("Salvar as infomações");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSalvar);
        botaoSalvar.setBounds(602, 152, 80, 98);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1090, 180, 147, 104);

        campoEtiqueta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoEtiqueta.setText("ETIQUETA");
        campoEtiqueta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEtiquetaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEtiquetaFocusLost(evt);
            }
        });
        campoEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEtiquetaActionPerformed(evt);
            }
        });
        getContentPane().add(campoEtiqueta);
        campoEtiqueta.setBounds(37, 221, 515, 72);

        campoCPF.setFont(new java.awt.Font("Perpetua", 0, 25)); // NOI18N
        campoCPF.setText("CPF");
        campoCPF.setMaximumSize(new java.awt.Dimension(515, 72));
        campoCPF.setMinimumSize(new java.awt.Dimension(515, 72));
        campoCPF.setPreferredSize(new java.awt.Dimension(515, 72));
        campoCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFFocusLost(evt);
            }
        });
        campoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPFActionPerformed(evt);
            }
        });
        getContentPane().add(campoCPF);
        campoCPF.setBounds(732, 129, 515, 72);

        campoSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoSenha.setText("SENHA");
        campoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSenhaFocusLost(evt);
            }
        });
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha);
        campoSenha.setBounds(732, 227, 515, 72);

        botaoParar.setBackground(new java.awt.Color(247, 75, 74));
        botaoParar.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        botaoParar.setForeground(new java.awt.Color(255, 255, 255));
        botaoParar.setSelected(true);
        botaoParar.setText("PARAR TRIAGEM");
        botaoParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPararActionPerformed(evt);
            }
        });
        getContentPane().add(botaoParar);
        botaoParar.setBounds(408, 529, 493, 87);

        botaoIniciar.setBackground(new java.awt.Color(112, 247, 111));
        botaoIniciar.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        botaoIniciar.setText("INICIAR");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoIniciar);
        botaoIniciar.setBounds(408, 405, 493, 87);


        botaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        botaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHomeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoHome);
        botaoHome.setBounds(1170, 600, 90, 70);

        campoNome.setFont(new java.awt.Font("Perpetua", 0, 25)); // NOI18N
        campoNome.setText("NOME");
        campoNome.setMaximumSize(new java.awt.Dimension(515, 72));
        campoNome.setMinimumSize(new java.awt.Dimension(515, 72));
        campoNome.setPreferredSize(new java.awt.Dimension(515, 72));
        campoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeFocusLost(evt);
            }
        });
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome);
        campoNome.setBounds(37, 125, 515, 72);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     BEREMIZ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, -10, 545, 155);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BeremizFundo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1280, 720);

        jTextField2.setFont(new java.awt.Font("Perpetua", 0, 25)); // NOI18N
        jTextField2.setText("CPF");
        jTextField2.setMaximumSize(new java.awt.Dimension(515, 72));
        jTextField2.setMinimumSize(new java.awt.Dimension(515, 72));
        jTextField2.setPreferredSize(new java.awt.Dimension(515, 72));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 180, 230, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Selecao selecao;
    Beremiz beremiz;
    @SuppressWarnings("deprecation")
	private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        ControllerUsuario shazam = new ControllerUsuario();
        Usuario usuario = new Usuario();
        usuario.setCpf(campoCPF.getText());
        usuario.setSenha(campoSenha.getText());
        usuario.setEtiqueta(campoEtiqueta.getText().toUpperCase());
        usuario.setNome(null);
        shazam.excluirUsuarioController();
        JOptionPane.showMessageDialog(null, shazam.salvarUsuarioController(usuario) );
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void campoEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEtiquetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEtiquetaActionPerformed

    private void campoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPFActionPerformed

    }//GEN-LAST:event_campoCPFActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void botaoPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPararActionPerformed

        backgroundThread.stop();
        shazam.pararTriagem();
        JOptionPane.showMessageDialog(null,"Triagem Parada!");
    }//GEN-LAST:event_botaoPararActionPerformed

    @SuppressWarnings("deprecation")
	private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        // Beremiz enter
        Usuario usuario = new Usuario();
        usuario.setCpf(campoCPF.getText());
        usuario.setSenha(campoSenha.getText());
        usuario.setTipo("Beremiz");
        usuario.setEtiqueta(campoEtiqueta.getText().toUpperCase());
        System.out.println("etiqueta usuario: " + usuario.getEtiqueta());
       // SeleniumRepositorio shazam = new SeleniumRepositorio();
        //JOptionPane.showMessageDialog(null,  shazam.triar(usuario));
        Runnable task = new Runnable() {
            GeralController shazam = new GeralController();
            @Override
            public void run() {
               shazam.beremiz(usuario);
            }

        };
        // Run the task in a background thread
        backgroundThread = new Thread(task);
        backgroundThread.start();
        //shazam.beremiz(usuario);
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusGained
       // TODO add your handling code here:
       if (campoNome.getText().equals("NOME")){
       campoNome.setText("");
       }
    }//GEN-LAST:event_campoNomeFocusGained

    private void campoNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusLost
        // TODO add your handling code here:
        
        if (campoNome.getText().equals("")){
            campoNome.setText("NOME");
        }
    }//GEN-LAST:event_campoNomeFocusLost

    private void campoEtiquetaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEtiquetaFocusGained
        // TODO add your handling code here:
         if (campoEtiqueta.getText().equals("ETIQUETA")){
       campoEtiqueta.setText("");
       }
    }//GEN-LAST:event_campoEtiquetaFocusGained

    private void campoEtiquetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEtiquetaFocusLost
        // TODO add your handling code here:
         if (campoEtiqueta.getText().equals("")){
            campoEtiqueta.setText("ETIQUETA");
        }
    }//GEN-LAST:event_campoEtiquetaFocusLost

    private void campoCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusGained
        // TODO add your handling code here:
         if (campoCPF.getText().equals("CPF")){
       campoCPF.setText("");
       }
    }//GEN-LAST:event_campoCPFFocusGained

    private void campoCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFFocusLost
        // TODO add your handling code here:
         if (campoCPF.getText().equals("")){
            campoCPF.setText("CPF");
        }
    }//GEN-LAST:event_campoCPFFocusLost

    private void campoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusGained
        // TODO add your handling code here:
         if (campoSenha.getText().equals("")){
       campoSenha.setText("12345");
    }//GEN-LAST:event_campoSenhaFocusGained
    }
    private void campoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusLost
        // TODO add your handling code here:
          if (campoCPF.getText().equals("")){
       campoCPF.setText("12345");
          }
    }//GEN-LAST:event_campoSenhaFocusLost

    private void botaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHomeActionPerformed
        // TODO add your handling code here:
        
        if(selecao == null){
		selecao = new Selecao();
		selecao.setLocationRelativeTo(null);
		selecao.setVisible(true);
                selecao.setResizable(false);
            dispose();
		}
		 else{
		selecao.setLocationRelativeTo(null);
		selecao.setVisible(true);
		selecao.setResizable(false);
		 }
    }//GEN-LAST:event_botaoHomeActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beremiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beremiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beremiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beremiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	new Beremiz().setVisible(true);

               
            }
            
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoHome;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JToggleButton botaoParar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoEtiqueta;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
